name: 'Generate .env file from Hashicorp Vault'
description: 'Get secrets from Vault and write to a .env file'

branding:
    icon: "bar-chart-2"
    color: "purple"

inputs:
  VAULT_ADDR:
    description: 'Vault url'
    required: true

  VAULT_USERNAME:
    description: 'Vault login username'
    required: true

  VAULT_PASSWORD:
    description: 'Vault login password'
    required: true

  VAULT_SECRETS_PATH:
    description: 'Vault secrets path'
    required: true

  ENV_FILE_NAME:
    description: 'Name of created env-file'
    required: false
    default: .env

runs:
  using: "composite"
  steps:
   - name: Install Hashicorp Vault
     shell: bash
     run: |
        curl -S -O https://releases.hashicorp.com/vault/1.19.5/vault_1.19.5_linux_amd64.zip
        unzip -u vault_1.19.5_linux_amd64.zip -d .
        chmod +x vault
        mv vault /usr/local/bin

   - name: Login to Hashicorp Vault
     shell: bash
     env:
       VAULT_ADDR: ${{ inputs.VAULT_ADDR }}
       VAULT_SKIP_VERIFY: 'true'
     run: |
       vault login \
         -no-print \
         -method=userpass \
         username=${{ inputs.VAULT_USERNAME }} \
         password=${{ inputs.VAULT_PASSWORD }}

   - name: Create env-file from Hashicorp Vault config
     shell: bash
     env:
       VAULT_ADDR: ${{ inputs.VAULT_ADDR }}
       VAULT_SKIP_VERIFY: 'true'
     run: |
        vault kv get -format=json ${{ inputs.VAULT_SECRETS_PATH }} \
        | jq -r ".data.data" \
        | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' \
        > ${{ inputs.ENV_FILE_NAME }}

